# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
       FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
       ROLE_ADMIN:       ROLE_USER
       ROLE_SUPER_ADMIN: ROLE_ADMIN


    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory: ~
        fos_userbundle:
           id: fos_user.user_provider.username_email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
           pattern: ^/
           form_login:
               check_path: /login_check
               login_path: /login
               provider: fos_userbundle
               always_use_default_target_path: false
               default_target_path:            /profile
              # user_referer:  true
           logout:
               path:    /logout
               target: /
              # provider: fos_userbundle
              # csrf_provider: form.csrf_provider

           anonymous:    true

           
        main:
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    access_control:
       - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/admin/, role: ROLE_ADMIN }
       - { path: ^/projects/add, role: ROLE_USER }
       - { path: ^/profile/skills, role: ROLE_USER }
       - { path: ^/profile/edit, role: ROLE_USER }
       - { path: ^/profile/password-reset, role: ROLE_USER }
       - { path: ^/profile/change-password, role: ROLE_USER }
       - { path: ^/u/*, role: ROLE_USER }
       - { path: ^/profile/freelaners, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/profile/projects, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/projects/*/edit, role: ROLE_USER }
       - { path: ^/message, role: ROLE_USER }
       - { path: ^/payments, role: ROLE_USER }
       - { path: ^/portfolios, role: ROLE_USER }
       - { path: ^/portfolio/*, role: ROLE_USER }
       - { path: ^/dashboard, role: ROLE_USER }